export default {

  workspaces: [
    {
      ws_name: '한글알림오십자가오면어떻게될까한글은왜이바이트일까',
      ws_id: 0,
      role_id: 1,
      is_fav: 0,
    },
    {
      ws_name: 'aaaaaaaaaaaaaaa',
      ws_id: 1,
      role_id: 2,
      is_fav: 0,
    },
    {
      ws_name: 'workspaceAdmin2',
      ws_id: 2,
      role_id: 1,
      is_fav: 1,
    },
    {
      ws_name: 'workspaceMember2',
      ws_id: 3,
      role_id: 2,
      is_fav: 1,
    },
    {
      ws_name: 'workspaceAdmin3',
      ws_id: 4,
      role_id: 1,
      is_fav: 0,
    },
    {
      ws_name: 'workspaceMember3',
      ws_id: 5,
      role_id: 2,
      is_fav: 0,
    },
    {
      ws_name: 'workspaceAdmin4',
      ws_id: 6,
      role_id: 1,
      is_fav: 1,
    },
    {
      ws_name: 'workspaceMember4',
      ws_id: 7,
      role_id: 2,
      is_fav: 1,
    },
    {
      ws_name: 'workspaceAdmin5',
      ws_id: 8,
      role_id: 1,
      is_fav: 0,
    },
    {
      ws_name: 'workspaceMember5',
      ws_id: 9,
      role_id: 2,
      is_fav: 0,
    },
  ],
  notifications: [
    {
      noti_id :0,
      title: 'WorkList Noti Test1',
      workspaceName: 'workspace2',
      desc: 'test Noti',
      type: 'board',
      endDate: '2021/06/22',
      ws_id: 0,
      noti_read:0,
    },
    {
      noti_id :1,
      title: 'WorkList Noti Test2',
      workspaceName: 'workspace2',
      desc: 'test Noti',
      type: 'board',
      endDate: '2021/06/22',
      ws_id: 0,
      noti_read:1,
    },
    {
      noti_id :2,
      title: 'Card Noti Test1',
      workspaceName: 'workspace1',
      desc: 'test Noti',
      type: 'card',
      endDate: '2233/06/30',
      ws_id: 1,
      noti_read:0,
    },
    {
      noti_id :3,
      title: 'Card Noti Test2',
      workspaceName: 'workspace1',
      desc: 'test Noti',
      type: 'card',
      endDate: '2233/06/30',
      ws_id: 1,
      noti_read:1,
    },
    {
      noti_id :4,
      title: 'todo Noti Test1',
      workspaceName: 'workspace2',
      desc: 'test Noti',
      type: 'todo',
      endDate: '2021/06/30',
      ws_id: 1,
      noti_read:0,
    },
    {
      noti_id :5,
      title: 'todo Noti Test2',
      workspaceName: 'workspace2',
      desc: 'test Noti',
      type: 'todo',
      endDate: '2021/06/30',
      ws_id: 1,
      noti_read:1,
    },
    {
      noti_id :6,
      title: 'Invite Noti Test1',
      workspaceName: 'workspace3',
      desc: 'test Noti',
      type: 'invite',
      endDate: '2021/2type/30',
      ws_id: 0,
      noti_read:0,
    },
    {
      noti_id :7,
      title: 'Invite Noti Test2',
      workspaceName: 'workspace3',
      desc: 'test Noti',
      type: 'invite',
      endDate: '2021/2type/30',
      ws_id: 0,
      noti_read:1,
    },
  ],
};
