const CalendarTestData = [
  {
    card_id: '1',
    card_name: 'card 1',
    card_desc : 'card1_desc',
    list_id : '1',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 30),
    card_end_date : new Date(2021, 7-1, 15),
  },
  {
    card_id: '2',
    card_name: 'card 2',
    card_desc : 'card1_desc',
    list_id : '1',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 30),
    card_end_date : new Date(2021, 7-1, 10),
  },
  {
    card_id: '3',
    card_name: 'card 3',
    card_desc : 'card1_desc',
    list_id : '1',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 30),
    card_end_date : new Date(2021, 7-1, 20),
  },
  {
    card_id: '4',
    card_name: 'card 4',
    card_desc : 'card1_desc',
    list_id : '1',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 15),
    card_end_date : new Date(2021, 6-1, 30),
  },
  {
    card_id: '5',
    card_name: 'card 5',
    card_desc : 'card1_desc',
    list_id : '2',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 30),
    card_end_date : new Date(2021, 7-1, 15),
  },
  {
    card_id: '6',
    card_name: 'card 1',
    card_desc : 'card1_desc',
    list_id : '2',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 30),
    card_end_date : new Date(2021, 7-1, 10),
  },
  {
    card_id: '7',
    card_name: 'card 1',
    card_desc : 'card1_desc',
    list_id : '2',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 30),
    card_end_date : new Date(2021, 7-1, 20),
  },
  {
    card_id: '8',
    card_name: 'card 1',
    card_desc : 'card1_desc',
    list_id : '2',
    ws_id : '1',
    card_start_date : new Date(2021, 6-1, 15),
    card_end_date : new Date(2021, 6-1, 30),
  }
]

export default CalendarTestData;