const CardModalData = {
  m_cards: [
    {
      card_id: 0,
      card_name: 'card1',
      card_desc: 'blabla',
      list_id: 0,
      ws_id: 0,
      card_st_date: '2021/06/01',
      card_isdone: 0,
    },
    {
      card_id: 1,
      card_name: 'card2',
      card_desc: 'blabla',
      list_id: 0,
      ws_id: 0,
      card_st_date: '2021/06/01',
      card_isdone: 0,
    },
    {
      card_id: 2,
      card_name: 'card3',
      card_desc: 'blabla',
      list_id: 1,
      ws_id: 1,
      card_st_date: '2021/06/01',
      card_isdone: 0,
    },
    {
      card_id: 3,
      card_name: 'card4',
      card_desc: 'blabla',
      list_id: 1,
      ws_id: 1,
      card_st_date: '2021/06/01',
      card_isdone: 0,
    },
    {
      card_id: 4,
      card_name: 'card5',
      card_desc: 'blabla',
      list_id: 2,
      ws_id: 2,
      card_st_date: '2021/06/01',
      card_isdone: 0,
    },
    {
      card_id: 5,
      card_name: 'card6',
      card_desc: 'blabla',
      list_id: 2,
      ws_id: 2,
      card_st_date: '2021/06/01',
      card_isdone: 0,
    },
  ],
  card_act: [
    {
      card_id: 0,
      act_id: 0,
      user_id: 'user01@naver.com',
      act_desc: 'blabla',
      islog: 0,
    },
    {
      card_id: 1,
      act_id: 1,
      user_id: 'user03@naver.com',
      act_desc: 'blabla',
      islog: 1,
    },
    {
      card_id: 2,
      act_id: 2,
      user_id: 'user02@naver.com',
      act_desc: 'blabla',
      islog: 0,
    },
    {
      card_id: 3,
      act_id: 3,
      user_id: 'user01@naver.com',
      act_desc: 'blabla',
      islog: 1,
    },
    {
      card_id: 4,
      act_id: 4,
      user_id: 'user03@naver.com',
      act_desc: 'blabla',
      islog: 0,
    },
    {
      card_id: 5,
      act_id: 5,
      user_id: 'user02@naver.com',
      act_desc: 'blabla',
      islog: 1,
    },

  ],
  card_mem: [
    {
      card_id: 0,
      user_id: ['user01@naver.com', 'user03@naver.com'],
    },
    {
      card_id: 1,
      user_id: ['user01@naver.com', 'user03@naver.com'],
    },
    {
      card_id: 2,
      user_id: ['user02@naver.com', 'user01@naver.com'],
    },
    {
      card_id: 3,
      user_id: ['user02@naver.com', 'user01@naver.com'],
    },
    {
      card_id: 4,
      user_id: ['user03@naver.com', 'user02@naver.com'],
    },
    {
      card_id: 5,
      user_id: ['user03@naver.com', 'user02@naver.com'],
    },
  ],
  card_todo: [
    {
      todo_id: 0,
      todo_name: 'todo1',
      card_id: 0,
      todo_st_date: '2021/06/01',
      todo_end_date: '2021/06/22',
      todo_isdone: 0,
    },
    {
      todo_id: 1,
      todo_name: 'todo2',
      card_id: 1,
      todo_st_date: '2021/06/23',
      todo_end_date: '2021/06/30',
      todo_isdone: 1,
    },
    {
      todo_id: 2,
      todo_name: 'todo3',
      card_id: 2,
      todo_st_date: '2021/06/01',
      todo_end_date: '2021/06/22',
      todo_isdone: 0,
    },
    {
      todo_id: 3,
      todo_name: 'todo4',
      card_id: 3,
      todo_st_date: '2021/06/23',
      todo_end_date: '2021/06/30',
      todo_isdone: 1,
    },
    {
      todo_id: 4,
      todo_name: 'todo5',
      card_id: 4,
      todo_st_date: '2021/06/01',
      todo_end_date: '2021/06/22',
      todo_isdone: 0,
    },
    {
      todo_id: 5,
      todo_name: 'todo6',
      card_id: 5,
      todo_st_date: '2021/06/23',
      todo_end_date: '2021/06/30',
      todo_isdone: 1,
    },
  ],
  card_file: [
    {
      card_id: 0,
      file_id: 0,
      file_name: 'blabla',
    },
    {
      card_id: 1,
      file_id: 1,
      file_name: 'blabla',
    },
    {
      card_id: 2,
      file_id: 2,
      file_name: 'blabla',
    },
    {
      card_id: 3,
      file_id: 3,
      file_name: 'blabla',
    },
    {
      card_id: 4,
      file_id: 4,
      file_name: 'blabla',
    },
    {
      card_id: 5,
      file_id: 5,
      file_name: 'blabla',
    },
  ],

};

export default CardModalData;