export default{
    workspace_modal:[
        {
            ws_id:0,
            ws_name:"workspace1",
            role:[
                {
                   user_id:"user01@naver.com",
                   user_name:"user01",
                   role_id:1
                },
            ],
            is_fav:0
        },
        {
            ws_id:0,
            ws_name:"workspace1",
            role:[
                {
                   user_id:"user03@naver.com",
                   user_name:"user03",
                   role_id:2
                },
            ],
            is_fav:0
        },
        {
            ws_id:1,
            ws_name:"workspace2",
            role:[
                {
                   user_id:"user02@naver.com",
                   user_name:"user02",
                   role_id:1
                },
            ],
            is_fav:0
        },
        {
            ws_id:1,
            ws_name:"workspace2",
            role:[
                {
                   user_id:"user01@naver.com",
                   user_name:"user01",
                   role_id:2
                },
            ],
            is_fav:1
        },
        {
            ws_id:2,
            ws_name:"workspace3",
            role:[
                {
                   user_id:"user03@naver.com",
                   user_name:"user03",
                   role_id:1
                },
            ],
            is_fav:0
        },
        {
            ws_id:2,
            ws_name:"workspace3",
            role:[
                {
                   user_id:"user02@naver.com",
                   user_name:"user02",
                   role_id:2
                },
            ],
            is_fav:1
        },
    ]
}
